version: '3.0'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: rds

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zkpr

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPIC_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    container_name: kfk
